# Generated by Django 4.1.1 on 2022-11-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('gen', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('popSize', models.IntegerField()),
                ('avgFit', models.FloatField()),
                ('stdDevFit', models.FloatField()),
                ('bestFit', models.FloatField()),
                ('adjFit', models.FloatField()),
                ('stag', models.IntegerField()),
            ],
        ),
    ]
